# Generated by Django 4.1.3 on 2022-11-20 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_rename_nome_email_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
